version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../logs:/app/logs
      - ../uploads:/app/uploads
    environment:
      - FLASK_CONFIG=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/crm
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crm

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - ../logs:/app/logs
    environment:
      - FLASK_CONFIG=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/crm
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - web
      - redis

  celery-beat:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: celery -A app.celery beat --loglevel=info
    volumes:
      - ../logs:/app/logs
    environment:
      - FLASK_CONFIG=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/crm
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - web
      - redis

volumes:
  postgres_data: 