"""Add missing organization fields

Revision ID: 1673dc18db38
Revises: d9aec0543af8
Create Date: 2025-04-20 20:34:54.295966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1673dc18db38'
down_revision = 'd9aec0543af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('fax')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address_line1', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('address_line2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('segment_tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('custom_fields', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('clv', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('engagement_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('churn_risk', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('upsell_potential', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('next_best_action', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('last_interaction', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('last_interaction')
        batch_op.drop_column('next_best_action')
        batch_op.drop_column('upsell_potential')
        batch_op.drop_column('churn_risk')
        batch_op.drop_column('engagement_score')
        batch_op.drop_column('clv')
        batch_op.drop_column('custom_fields')
        batch_op.drop_column('segment_tags')
        batch_op.drop_column('status')
        batch_op.drop_column('country')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address_line2')
        batch_op.drop_column('address_line1')
        batch_op.drop_column('phone')
        batch_op.drop_column('primary_email')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fax', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
