"""empty message

Revision ID: d9aec0543af8
Revises: 5702e3b911b2
Create Date: 2025-04-20 15:54:53.627419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9aec0543af8'
down_revision = '5702e3b911b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_contacts')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('interests',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('probability',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('expected_close_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('contact_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'contacts', ['contact_id'], ['id'])

    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('expected_close_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('probability',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('interests',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('_alembic_tmp_contacts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), nullable=False),
    sa.Column('stage', sa.VARCHAR(length=50), nullable=True),
    sa.Column('stage_changed_at', sa.DATETIME(), nullable=True),
    sa.Column('stage_history', sa.TEXT(), nullable=True),
    sa.Column('customer_since', sa.DATETIME(), nullable=True),
    sa.Column('lifetime_value', sa.FLOAT(), nullable=True),
    sa.Column('customer_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('deal_value', sa.FLOAT(), nullable=True),
    sa.Column('probability', sa.INTEGER(), nullable=True),
    sa.Column('expected_close_date', sa.DATE(), nullable=True),
    sa.Column('budget', sa.VARCHAR(length=50), nullable=True),
    sa.Column('requirements', sa.TEXT(), nullable=True),
    sa.Column('interested_in', sa.VARCHAR(length=255), nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), nullable=True),
    sa.Column('source_origin', sa.VARCHAR(length=100), nullable=True),
    sa.Column('source_channel', sa.VARCHAR(length=100), nullable=True),
    sa.Column('next_follow_up', sa.DATETIME(), nullable=True),
    sa.Column('last_contact_date', sa.DATETIME(), nullable=True),
    sa.Column('middle_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('nickname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('birthday', sa.DATE(), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=20), nullable=True),
    sa.Column('marital_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), nullable=True),
    sa.Column('work_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('home_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('fax', sa.VARCHAR(length=20), nullable=True),
    sa.Column('alternate_email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('linkedin', sa.VARCHAR(length=200), nullable=True),
    sa.Column('twitter', sa.VARCHAR(length=200), nullable=True),
    sa.Column('facebook', sa.VARCHAR(length=200), nullable=True),
    sa.Column('instagram', sa.VARCHAR(length=200), nullable=True),
    sa.Column('github', sa.VARCHAR(length=200), nullable=True),
    sa.Column('address_line1', sa.VARCHAR(length=200), nullable=True),
    sa.Column('address_line2', sa.VARCHAR(length=200), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('company_size', sa.VARCHAR(length=50), nullable=True),
    sa.Column('industry', sa.VARCHAR(length=100), nullable=True),
    sa.Column('website', sa.VARCHAR(length=200), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('interests', sa.VARCHAR(length=500), nullable=True),
    sa.Column('skills', sa.TEXT(), nullable=True),
    sa.Column('education', sa.TEXT(), nullable=True),
    sa.Column('work_history', sa.TEXT(), nullable=True),
    sa.Column('preferences', sa.TEXT(), nullable=True),
    sa.Column('tags', sa.VARCHAR(length=500), nullable=True),
    sa.Column('custom_fields', sa.TEXT(), nullable=True),
    sa.Column('mobile', sa.VARCHAR(length=20), nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_contacts_email')
    )
    # ### end Alembic commands ###
