"""Add end_date and update interaction fields

Revision ID: e93dd1a5ef27
Revises: 6d8ed25ac006
Create Date: 2025-04-19 14:30:43.631983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93dd1a5ef27'
down_revision = '6d8ed25ac006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ai_analysis', sa.Text(), nullable=True))
        batch_op.drop_column('subject')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('ai_analysis')
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###
